### ISSUE TITLE
Question about firmwares

### ISSUE THREAD

**Issue by Testbild-synth** [MiguelDeTrool/Apeks#1]
Hey, great work! 
Im building your module right now and I'm getting kind of lost with the firmware upload, especially because I've never worked with blue pills before and they seem to be a bit peculiar with uploading things (boot jumpers, bootloader and programm flashing etc).

So I'm kind of confused as to what the different firmwares are that you have compiled, could you maybe add a bit of documentation to what they are and the upload process in general?
For my bluepill board, the only combination of firmwares that I managed to upload correctly is the 8002000 bootloader with the no_eastereggs firmware. Not sure what the differences here is.

**Comment by MiguelDeTrool** [comment]
Hello, you are probably using a 64kB bluepill (part number STM32F103C8T6), and not the original 128kB (CBT6). The 0x08002000_NoEasterEgg.hex version makes the firmware as small as possible by removing the easter egg, to allow the use of 64kB parts. It is still untested.

As for documentation about uploading, you can find many tutorials concerning how to uploaded precompiled firmware to STM32 boards. The easiest method is probably to use an STLink with the STM32CubeProgrammer, which Kristian Blasol explains well in his [video here](https://youtu.be/q5mbdBCou-k?t=4879).

**Comment by MiguelDeTrool** [comment]
Hello, you are probably using a 64kB bluepill (part number STM32F103C8T6), and not the original 128kB (CBT6). The 0x08002000_NoEasterEgg.hex version makes the firmware as small as possible by removing the easter egg, to allow the use of 64kB parts. It is still untested.

As for documentation about uploading, you can find many tutorials concerning how to uploaded precompiled firmware to STM32 boards. The easiest method is probably to use an STLink with the STM32CubeProgrammer, which Kristian Blasol explains well in his [video here](https://youtu.be/q5mbdBCou-k?t=4879).

**Comment by Testbild-synth** [comment]
@MiguelDeTrool thanks for the reply. Yes I have a 64k bluepill, and the 08002000 NoEasterEgg works with it :+1: 
The thing is now that for me, the output 1 and 2 are switched. (trig switches and lights are fine, just the output jacks).
Simple to fix by cutting the trace and soldering two cables, but idk if that is specific to the 08002000 version or a general issue you might wanna look into. Either way my unit is fully working now, thanks again for the great work!

**Comment by MiguelDeTrool** [comment]
The 0x08002000 version was developed on a prototype, hence why it is untested. The DAC codes need to be switched in the firmware and recompiled. But you can indeed also just switch it in hardware by cutting some traces and adding jumpers.

**Comment by MiguelDeTrool** [comment]
I'm still doing some testing with a 64kB board, and having some struggles. I've added a minified firmware with switched channels, you can try both, and see if one works.
